Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 8089, host: 8089

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus   = "2"
    vb.customize ["modifyvm", :id, "--vram", "8"]
  end

  config.vm.provision "shell" do |s|
    s.env  = { "SPLUNK_PASSWORD":ENV['SPLUNK_PASSWORD'] }
    s.path = "provisioner.sh"
  end
end
