apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: splunk-forwarder-daemonset
  namespace: security-tt
spec:
  selector:
    matchLabels:
      app: splunk-forwarder-app
  template:
    metadata:
      labels:
         app: splunk-forwarder-app
    spec:
      containers:
      - name: splunk-forwarder-pod
        image: {{REGISTRY_IP}}/splunk_fwdr_7:v1
        resources:
          limits:
            memory: 2048Mi
            cpu: "1.5"
          requests:
            memory: 512Mi
            cpu: "0.5"
        env:
        - name: SPLUNK_START_ARGS
          value: "--accept-license --answer-yes"
        - name: SPLUNK_USER
          value: root
        volumeMounts:
        - mountPath: /var/run/docker.sock
          readOnly: true
          name: docker-socket
        - mountPath: /var/lib/docker/containers
          readOnly: true
          name: container-logs
        - mountPath: /opt/staging/splunk/etc/apps/splunkclouduf/default
          name: splunk-config
        - mountPath: /var/log/containers
          readOnly: true
          name: pod-logs
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: container-logs
          hostPath:
            path: /var/lib/docker/containers
        - name: pod-logs
          hostPath:
            path: /var/log/containers
        - name: splunk-config
          configMap:
            name: splunk-forwarder-config