apiVersion: v1
kind: Service
metadata:
  name: splunk-svc
  namespace: security-tt
spec:
  selector:
    app: splunk-app
  type: NodePort
  ports:
  - nodePort: 30800
    port: 8000
    targetPort: 8000
